# Generated by Django 4.1.2 on 2022-10-27 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='date_due',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='date_due',
        ),
    ]
