# Generated by Django 4.1.2 on 2022-10-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='inputprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='phone_number',
        ),
    ]
